name: Deploy to Dockerhub

on:
  workflow_dispatch:
    # Enable manual run
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  push_to_registry:
    #needs: build
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          tags: 'jahurtado11/micro-users'
          
